### ISSUE TITLE
OpenWRT  for UFI103S

### ISSUE THREAD

**Issue by chautruongthinh** [zfdx123/zfdx123#1]
Did you get openwrt modem with UFI103S_V5??

**Comment by zfdx123** [comment]
> Did you get openwrt modem with UFI103S_V5??

No, I haven't seen V5 and my v3 is broken.

**Comment by zfdx123** [comment]
OpenWRT doesn't work perfectly, and there is a lede branch that you can explore

**Comment by chautruongthinh** [comment]
I tried to compile Handsomemod but modem not work for UFI103S_V5.

I replaced stock firmware from Android and i got SIM Missing

**Comment by chautruongthinh** [comment]
I fixed modem for UFI103S_V5. 

![Screenshot from 2023-07-02 14-00-31](https://github.com/HandsomeMod/HandsomeMod/assets/1763903/6c503e53-be68-4ea4-bd29-e93cc1b2615c)
